services:
  - type: web
    name: youtube-summarizer
    runtime: python
    region: singapore
    plan: starter
    buildCommand: "apt-get update && apt-get install -y wget gnupg ca-certificates libxss1 libgconf-2-4 libxtst6 libxrandr2 libasound2 libpangocairo-1.0-0 libatk1.0-0 libcairo-gobject2 libgtk-3-0 libgdk-pixbuf2.0-0 && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google.list && apt-get update && apt-get install -y google-chrome-stable && uv sync --frozen && uv cache prune --ci && playwright install chromium"
    startCommand: "uv run uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
      - key: GEMINI_API_KEY
        sync: false
      - key: FAL_KEY
        sync: false