blocks = [
    {
        "object": "block",
        "id": "144bb2c6-d133-812b-964c-d485f92e7b19",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:19:00.000Z",
        "last_edited_time": "2024-11-20T13:19:00.000Z",
        "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {
            "rich_text": [
                {"type": "text", "text": {"content": "A function ", "link": None}, "plain_text": "A function ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "f(x)"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "f(x)", "href": None},
                {"type": "text", "text": {"content": " is convex if, for any two points ", "link": None}, "plain_text": " is convex if, for any two points ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "x_1"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "x_1", "href": None},
                {"type": "text", "text": {"content": " and ", "link": None}, "plain_text": " and ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "x_2"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "x_2", "href": None},
                {"type": "text", "text": {"content": " in its domain and any ", "link": None}, "plain_text": " in its domain and any ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "\\lambda"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "\\lambda", "href": None},
                {"type": "text", "text": {"content": " such that ", "link": None}, "plain_text": " such that ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "0 \\leq \\lambda \\leq 1"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "0 \\leq \\lambda \\leq 1", "href": None},
                {"type": "text", "text": {"content": ", the following holds:\n", "link": None}, "plain_text": ", the following holds:\n", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "f(\\lambda x_1 + (1 - \\lambda)x_2) \\leq \\lambda f(x_1) + (1 - \\lambda)f(x_2)"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "f(\\lambda x_1 + (1 - \\lambda)x_2) \\leq \\lambda f(x_1) + (1 - \\lambda)f(x_2)", "href": None},
            ],
            "color": "default",
        },
    },
    {"object": "block", "id": "144bb2c6-d133-814e-8bf1-f21f1f1dc7bf", "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"}, "created_time": "2024-11-20T13:19:00.000Z", "last_edited_time": "2024-11-20T13:19:00.000Z", "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"}, "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"}, "has_children": False, "archived": False, "in_trash": False, "type": "bulleted_list_item", "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": "This implies that the line segment between any two points on the graph of the function lies above the graph.", "link": None}, "plain_text": "This implies that the line segment between any two points on the graph of the function lies above the graph.", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None}], "color": "default"}},
    {
        "object": "block",
        "id": "144bb2c6-d133-815d-8f62-f210bd111fc9",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:19:00.000Z",
        "last_edited_time": "2024-11-20T13:19:00.000Z",
        "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {
            "rich_text": [
                {"type": "text", "text": {"content": "A set ", "link": None}, "plain_text": "A set ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "C"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "C", "href": None},
                {"type": "text", "text": {"content": " is convex if, for any two points ", "link": None}, "plain_text": " is convex if, for any two points ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "x_1, x_2 \\in C"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "x_1, x_2 \\in C", "href": None},
                {"type": "text", "text": {"content": ", the line segment connecting them is entirely contained within ", "link": None}, "plain_text": ", the line segment connecting them is entirely contained within ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "C"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "C", "href": None},
                {"type": "text", "text": {"content": ". Mathematically, for any ", "link": None}, "plain_text": ". Mathematically, for any ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "\\lambda"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "\\lambda", "href": None},
                {"type": "text", "text": {"content": " such that ", "link": None}, "plain_text": " such that ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "0 \\leq \\lambda \\leq 1"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "0 \\leq \\lambda \\leq 1", "href": None},
                {"type": "text", "text": {"content": ", the point ", "link": None}, "plain_text": ", the point ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "\\lambda x_1 + (1 - \\lambda)x_2"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "\\lambda x_1 + (1 - \\lambda)x_2", "href": None},
                {"type": "text", "text": {"content": " is also in ", "link": None}, "plain_text": " is also in ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "C"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "C", "href": None},
                {"type": "text", "text": {"content": ".", "link": None}, "plain_text": ".", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
            ],
            "color": "default",
        },
    },
    {"object": "block", "id": "144bb2c6-d133-81e0-b6b0-c38b10083567", "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"}, "created_time": "2024-11-20T13:19:00.000Z", "last_edited_time": "2024-11-20T13:37:00.000Z", "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"}, "last_edited_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "has_children": False, "archived": False, "in_trash": False, "type": "equation", "equation": {"expression": "\n\\text{minimize } f(x)\n\n"}},
    {
        "object": "block",
        "id": "144bb2c6-d133-8152-878e-ffe0f1d4dbac",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:19:00.000Z",
        "last_edited_time": "2024-11-20T13:19:00.000Z",
        "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {
            "rich_text": [
                {"type": "text", "text": {"content": "Here, ", "link": None}, "plain_text": "Here, ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "f(x)"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "f(x)", "href": None},
                {"type": "text", "text": {"content": " is a convex function, and ", "link": None}, "plain_text": " is a convex function, and ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
                {"type": "equation", "equation": {"expression": "C"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "C", "href": None},
                {"type": "text", "text": {"content": " is a convex set defined by linear equality and inequality constraints.", "link": None}, "plain_text": " is a convex set defined by linear equality and inequality constraints.", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
            ],
            "color": "default",
        },
    },
    {
        "object": "block",
        "id": "144bb2c6-d133-81b3-bbce-e7ede769fc5e",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:19:00.000Z",
        "last_edited_time": "2024-11-20T13:19:00.000Z",
        "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": "For simple convex problems, analytical solutions may be possible using calculus, such as setting the gradient to zero to find critical points.", "link": None}, "plain_text": "For simple convex problems, analytical solutions may be possible using calculus, such as setting the gradient to zero to find critical points.", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None}], "color": "default"},
    },
    {
        "object": "block",
        "id": "144bb2c6-d133-81b0-ac3e-ebe8d6d30ec5",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:19:00.000Z",
        "last_edited_time": "2024-11-20T13:19:00.000Z",
        "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": "A first-order iterative optimization algorithm for finding the minimum of a convex function. It uses the gradient of the function to take steps proportional to the negative of the gradient at the current point.", "link": None}, "plain_text": "A first-order iterative optimization algorithm for finding the minimum of a convex function. It uses the gradient of the function to take steps proportional to the negative of the gradient at the current point.", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None}], "color": "default"},
    },
    {
        "object": "block",
        "id": "144bb2c6-d133-8154-805e-f565dba57f00",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:19:00.000Z",
        "last_edited_time": "2024-11-20T13:19:00.000Z",
        "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": "A second-order method that uses both the gradient and the Hessian matrix to find the optimal solution. It converges faster than gradient descent for well-behaved convex functions.", "link": None}, "plain_text": "A second-order method that uses both the gradient and the Hessian matrix to find the optimal solution. It converges faster than gradient descent for well-behaved convex functions.", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None}], "color": "default"},
    },
    {
        "object": "block",
        "id": "144bb2c6-d133-8187-93b5-ca6d62af139f",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:19:00.000Z",
        "last_edited_time": "2024-11-20T13:19:00.000Z",
        "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": "These are more advanced methods used for large-scale convex optimization problems. They work from the interior of the feasible region and move towards the boundary.", "link": None}, "plain_text": "These are more advanced methods used for large-scale convex optimization problems. They work from the interior of the feasible region and move towards the boundary.", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None}], "color": "default"},
    },
    {
        "object": "block",
        "id": "144bb2c6-d133-81e2-8234-c6e10d81fc69",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:19:00.000Z",
        "last_edited_time": "2024-11-20T13:19:00.000Z",
        "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": "Convex problems often have a dual problem associated with them, and solving the dual can provide insights or even solutions to the primal problem.", "link": None}, "plain_text": "Convex problems often have a dual problem associated with them, and solving the dual can provide insights or even solutions to the primal problem.", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None}], "color": "default"},
    },
    {
        "object": "block",
        "id": "144bb2c6-d133-81ba-948a-fe108665005e",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:19:00.000Z",
        "last_edited_time": "2024-11-20T13:19:00.000Z",
        "created_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": "Various software packages and libraries, such as CVXOPT, MOSEK, and others, can solve convex optimization problems efficiently.", "link": None}, "plain_text": "Various software packages and libraries, such as CVXOPT, MOSEK, and others, can solve convex optimization problems efficiently.", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None}], "color": "default"},
    },
    {"object": "block", "id": "144bb2c6-d133-8095-8103-f3e032a0cd0b", "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"}, "created_time": "2024-11-20T13:37:00.000Z", "last_edited_time": "2024-11-20T13:37:00.000Z", "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "last_edited_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "has_children": False, "archived": False, "in_trash": False, "type": "bookmark", "bookmark": {"caption": [], "url": "https://arxiv.org/abs/2410.17434"}},
    {"object": "block", "id": "144bb2c6-d133-807c-8abc-fcba998bd440", "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"}, "created_time": "2024-11-20T13:37:00.000Z", "last_edited_time": "2024-11-20T13:37:00.000Z", "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "last_edited_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "has_children": False, "archived": False, "in_trash": False, "type": "bookmark", "bookmark": {"caption": [], "url": "https://huggingface.co/spaces/Vision-CAIR/LongVU"}},
    {"object": "block", "id": "144bb2c6-d133-8073-aac5-c53b3fc61ff2", "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"}, "created_time": "2024-11-20T13:37:00.000Z", "last_edited_time": "2024-11-21T02:11:00.000Z", "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "last_edited_by": {"object": "user", "id": "94ad1e70-a3c1-4e37-aa63-116b7fec0a8f"}, "has_children": False, "archived": False, "in_trash": False, "type": "link_preview", "link_preview": {"url": "https://github.com/Vision-CAIR/LongVU"}},
    {
        "object": "block",
        "id": "144bb2c6-d133-8032-aa4e-dc09f4142ed3",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:37:00.000Z",
        "last_edited_time": "2024-11-20T13:37:00.000Z",
        "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"},
        "last_edited_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "image",
        "image": {"caption": [], "type": "file", "file": {"url": "https://prod-files-secure.s3.us-west-2.amazonaws.com/be6efff9-e886-4a28-8814-acf62067a9f6/adac33f0-f75e-4545-8303-ad322b2eaf82/image.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45FSPPWI6X%2F20241121%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20241121T021257Z&X-Amz-Expires=3600&X-Amz-Signature=5356342eeaa1814f586a07e23f5ccf4eeb850b03b95973caae37046ebddfaec8&X-Amz-SignedHeaders=host&x-id=GetObject", "expiry_time": "2024-11-21T03:12:57.163Z"}},
    },
    {
        "object": "block",
        "id": "144bb2c6-d133-8000-b8f9-de61ad9376d3",
        "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"},
        "created_time": "2024-11-20T13:37:00.000Z",
        "last_edited_time": "2024-11-20T13:37:00.000Z",
        "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"},
        "last_edited_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "paragraph",
        "paragraph": {
            "rich_text": [
                {
                    "type": "text",
                    "text": {"content": "Given a densely sampled video frames, LongVU first utilizes sDINOv2 prior to remove redundant frames, and fuse the remaining frame features from both SigLIP and DINOv2. Then we selectively reduce visual tokens via cross-modal query. Finally, it conducts spatial token compression based on temporal dependencies to further meet the limited context length of LLMs.", "link": None},
                    "plain_text": "Given a densely sampled video frames, LongVU first utilizes sDINOv2 prior to remove redundant frames, and fuse the remaining frame features from both SigLIP and DINOv2. Then we selectively reduce visual tokens via cross-modal query. Finally, it conducts spatial token compression based on temporal dependencies to further meet the limited context length of LLMs.",
                    "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"},
                    "href": None,
                },
            ],
            "color": "default",
        },
    },
    {"object": "block", "id": "144bb2c6-d133-8011-9cf7-cefc60efce6b", "parent": {"type": "page_id", "page_id": "144bb2c6-d133-8068-befd-fb9e08242891"}, "created_time": "2024-11-20T13:37:00.000Z", "last_edited_time": "2024-11-20T13:37:00.000Z", "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "last_edited_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "has_children": False, "archived": False, "in_trash": False, "type": "paragraph", "paragraph": {"rich_text": [], "color": "default"}},
]
import os
from typing import Any, Dict, List, Optional, Tuple

import requests
from dotenv import load_dotenv
from notion_client import Client

from notion_formatter import BlockProcessor, NotionAPI

load_dotenv()

NOTION_TOKEN = os.getenv("NOTION_TOKEN")
PAGE_ID = "145bb2c6d13380b29fb4f636717263a7"


notion = NotionAPI(NOTION_TOKEN, PAGE_ID)


blocks = notion.read_blocks(PAGE_ID)
print(blocks)
blocks_with_rich_text = [block for block in blocks if block.get(block["type"]).get("rich_text")]


print(blocks_with_rich_text[0])
converted_block = BlockProcessor.convert_latex_block(blocks_with_rich_text[0])
print(converted_block)

# Fix the update_block call by properly formatting the request
rich_text = converted_block["paragraph"]["rich_text"]
for i in range(len(blocks_with_rich_text)):
    response = notion.update_block(block=blocks_with_rich_text[i], rich_text=rich_text)
print(response)

[
    {
        "object": "block",
        "id": "d3295e3a-77c0-45fc-81e7-79ea1bccb0ab",
        "parent": {"type": "page_id", "page_id": "145bb2c6-d133-80b2-9fb4-f636717263a7"},
        "created_time": "2024-11-21T03:07:00.000Z",
        "last_edited_time": "2024-11-21T04:15:00.000Z",
        "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"},
        "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "paragraph",
        "paragraph": {
            "rich_text": [
                {"type": "text", "text": {"content": "A function ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "A function ", "href": None},
                {"type": "equation", "equation": {"expression": "f(x)"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "f(x)", "href": None},
                {"type": "text", "text": {"content": " is convex if, for any two points ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": " is convex if, for any two points ", "href": None},
                {"type": "equation", "equation": {"expression": "x_1"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "x_1", "href": None},
                {"type": "text", "text": {"content": " and ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": " and ", "href": None},
                {"type": "equation", "equation": {"expression": "x_2"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "x_2", "href": None},
                {"type": "text", "text": {"content": " in its domain and any ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": " in its domain and any ", "href": None},
                {"type": "equation", "equation": {"expression": "\\lambda"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "\\lambda", "href": None},
                {"type": "text", "text": {"content": " such that ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": " such that ", "href": None},
                {"type": "equation", "equation": {"expression": "0 \\leq \\lambda \\leq 1"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "0 \\leq \\lambda \\leq 1", "href": None},
                {"type": "text", "text": {"content": ", the following holds", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": ", the following holds", "href": None},
            ],
            "color": "default",
        },
    },
    {
        "object": "block",
        "id": "84f3c178-0515-40cd-9501-5e271889f482",
        "parent": {"type": "page_id", "page_id": "145bb2c6-d133-80b2-9fb4-f636717263a7"},
        "created_time": "2024-11-21T03:07:00.000Z",
        "last_edited_time": "2024-11-21T03:07:00.000Z",
        "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"},
        "last_edited_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"},
        "has_children": False,
        "archived": False,
        "in_trash": False,
        "type": "bulleted_list_item",
        "bulleted_list_item": {"rich_text": [{"type": "text", "text": {"content": "A function \\( f(x) \\) is convex if, for any two points \\( x_1 \\) and \\( x_2 \\) in its domain and any \\( \\lambda \\) such that \\( 0 \\leq \\lambda \\leq 1 \\), the following holds", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "A function \\( f(x) \\) is convex if, for any two points \\( x_1 \\) and \\( x_2 \\) in its domain and any \\( \\lambda \\) such that \\( 0 \\leq \\lambda \\leq 1 \\), the following holds", "href": None}], "color": "default"},
    },
    {"object": "block", "id": "76276272-f697-4ca5-ae07-365935ee755f", "parent": {"type": "page_id", "page_id": "145bb2c6-d133-80b2-9fb4-f636717263a7"}, "created_time": "2024-11-21T03:07:00.000Z", "last_edited_time": "2024-11-21T03:07:00.000Z", "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "last_edited_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"}, "has_children": False, "archived": False, "in_trash": False, "type": "paragraph", "paragraph": {"rich_text": [], "color": "default"}},
]
{
    "object": "block",
    "id": "d3295e3a-77c0-45fc-81e7-79ea1bccb0ab",
    "parent": {"type": "page_id", "page_id": "145bb2c6-d133-80b2-9fb4-f636717263a7"},
    "created_time": "2024-11-21T03:07:00.000Z",
    "last_edited_time": "2024-11-21T04:15:00.000Z",
    "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"},
    "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
    "has_children": False,
    "archived": False,
    "in_trash": False,
    "type": "paragraph",
    "paragraph": {
        "rich_text": [
            {"type": "text", "text": {"content": "A function ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "A function ", "href": None},
            {"type": "equation", "equation": {"expression": "f(x)"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "f(x)", "href": None},
            {"type": "text", "text": {"content": " is convex if, for any two points ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": " is convex if, for any two points ", "href": None},
            {"type": "equation", "equation": {"expression": "x_1"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "x_1", "href": None},
            {"type": "text", "text": {"content": " and ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": " and ", "href": None},
            {"type": "equation", "equation": {"expression": "x_2"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "x_2", "href": None},
            {"type": "text", "text": {"content": " in its domain and any ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": " in its domain and any ", "href": None},
            {"type": "equation", "equation": {"expression": "\\lambda"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "\\lambda", "href": None},
            {"type": "text", "text": {"content": " such that ", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": " such that ", "href": None},
            {"type": "equation", "equation": {"expression": "0 \\leq \\lambda \\leq 1"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "0 \\leq \\lambda \\leq 1", "href": None},
            {"type": "text", "text": {"content": ", the following holds", "link": None}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": ", the following holds", "href": None},
        ],
        "color": "default",
    },
}
{
    "object": "block",
    "id": "d3295e3a-77c0-45fc-81e7-79ea1bccb0ab",
    "parent": {"type": "page_id", "page_id": "145bb2c6-d133-80b2-9fb4-f636717263a7"},
    "created_time": "2024-11-21T03:07:00.000Z",
    "last_edited_time": "2024-11-21T04:15:00.000Z",
    "created_by": {"object": "user", "id": "3c876d9c-6506-491d-ae3f-65fa9933efaa"},
    "last_edited_by": {"object": "user", "id": "fc782041-63ee-4257-860a-f10c2b0325b7"},
    "has_children": False,
    "archived": False,
    "in_trash": False,
    "type": "paragraph",
    "paragraph": {
        "rich_text": [
            {"type": "text", "text": {"content": "A function ", "link": None}, "plain_text": "A function ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
            {"type": "equation", "equation": {"expression": "f(x)"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "f(x)", "href": None},
            {"type": "text", "text": {"content": " is convex if, for any two points ", "link": None}, "plain_text": " is convex if, for any two points ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
            {"type": "equation", "equation": {"expression": "x_1"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "x_1", "href": None},
            {"type": "text", "text": {"content": " and ", "link": None}, "plain_text": " and ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
            {"type": "equation", "equation": {"expression": "x_2"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "x_2", "href": None},
            {"type": "text", "text": {"content": " in its domain and any ", "link": None}, "plain_text": " in its domain and any ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
            {"type": "equation", "equation": {"expression": "\\lambda"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "\\lambda", "href": None},
            {"type": "text", "text": {"content": " such that ", "link": None}, "plain_text": " such that ", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
            {"type": "equation", "equation": {"expression": "0 \\leq \\lambda \\leq 1"}, "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "plain_text": "0 \\leq \\lambda \\leq 1", "href": None},
            {"type": "text", "text": {"content": ", the following holds", "link": None}, "plain_text": ", the following holds", "annotations": {"bold": False, "italic": False, "strikethrough": False, "underline": False, "code": False, "color": "default"}, "href": None},
        ],
        "color": "default",
    },
}
{"object": "error", "status": 400, "code": "validation_error", "message": "Expected block type bulleted_list_item in request body", "request_id": "05ceabbb-c7f7-4ffb-8ee7-f6e1d4188cc3"}
